version: '3.8'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: XXXXXXXXXXX
      MYSQL_DATABASE: XXXXXXXXXX
      MYSQL_USER: XXXXXXXX
      MYSQL_PASSWORD: XXXXXXXX
    ports:
      - "3307:3306"
